---
version: '3'

services:
    web:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: translatable
        environment:
            XDEBUG_CONFIG: 'idekey=PHPSTORM'
            XDEBUG_MODE: 'off'
            PHP_IDE_CONFIG: 'serverName=localhost'
            DOCROOT: '/var/www/application/tests/_support/project/public'
            HOST_UID: 1000
            HOST_GID: 1000
            APP_ENV: test
        ports:
            - 80:80
            - 443:443
        volumes:
            - .:/var/www/application
            - ~/.composer:/var/www/.composer
